repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        exclude: ^vendor/
      - id: check-json
        exclude: ^vendor/
  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc
        exclude: ^vendor/
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        exclude: ^vendor/
      - id: go-imports
        exclude: ^vendor/
