# 会报错 同一个 pod 共享网络协议栈 所以不能监听同一个端口 跟 containerPort 没有关系
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-1
        image: nginx:1.14.2
        ports:
        - name: nginx-1-port
          containerPort: 80
      - name: nginx-2
        image: nginx:1.14.2
        ports:
        - name: nginx-2-port
          containerPort: 81
