apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # At every minute.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: cargo.caicloud.io/caicloud/busybox:latest
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
