apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 5
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: cargo.caicloud.io/caicloud/perl:latest
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
