apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: tutorial
spec:
  containers:
  - name: nginx
    image: nginx:1.13
    resources:
      requests:
        cpu: "2"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "1Gi"
